//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.db_logistica
{
    using System;
    using System.Collections.Generic;
    
    public partial class ficha
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ficha()
        {
            this.fichaFlights = new HashSet<fichaFlights>();
            this.volunteers = new HashSet<volunteers>();
            this.vehicles = new HashSet<vehicles>();
            this.staff = new HashSet<staff>();
            this.university = new HashSet<university>();
        }
    
        public string id { get; set; }
        public Nullable<System.DateTime> startingDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string officeArrivalDate { get; set; }
        public string officeLeaveDate { get; set; }
        public Nullable<short> totalStudents { get; set; }
        public string cityTour { get; set; }
        public Nullable<int> compound { get; set; }
        public Nullable<int> community { get; set; }
        public int program { get; set; }
        public Nullable<int> subProgram { get; set; }
        public Nullable<System.DateTime> priDtop { get; set; }
        public Nullable<System.DateTime> priDted { get; set; }
        public Nullable<System.DateTime> secDtop { get; set; }
        public Nullable<System.DateTime> secDted { get; set; }
    
        public virtual community community1 { get; set; }
        public virtual compound compound1 { get; set; }
        public virtual programs programs { get; set; }
        public virtual programs programs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fichaFlights> fichaFlights { get; set; }
        public virtual itinerary itinerary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<volunteers> volunteers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vehicles> vehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff> staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<university> university { get; set; }
    }
}
