//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.db_logistica
{
    using System;
    using System.Collections.Generic;
    
    public partial class fichaFlights
    {
        public string id { get; set; }
        public short type { get; set; }
        public System.DateTime arrivalTime { get; set; }
        public short totalStudents { get; set; }
        public string ficha { get; set; }
    
        public virtual ficha ficha1 { get; set; }
    }
}
