//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.db_logistica
{
    using System;
    using System.Collections.Generic;
    
    public partial class securityMedicines
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public short quantity { get; set; }
        public System.DateTime expirationDate { get; set; }
        public string especs { get; set; }
        public float cost { get; set; }
    }
}
