//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.db_logistica
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staff()
        {
            this.spokenLanguage = new HashSet<spokenLanguage>();
            this.ficha = new HashSet<ficha>();
            this.programs = new HashSet<programs>();
        }
    
        public string username { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string id { get; set; }
        public short sex { get; set; }
        public System.DateTime bornDate { get; set; }
        public Nullable<short> age { get; set; }
        public string citizenship { get; set; }
        public string bloodType { get; set; }
        public string maritalStatus { get; set; }
        public string cellphoneNumber { get; set; }
        public string email { get; set; }
        public string university { get; set; }
        public string allergies { get; set; }
        public string medicalCondition { get; set; }
        public string emergencyContact { get; set; }
        public string career { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> contractDate { get; set; }
        public Nullable<System.DateTime> interviewDate { get; set; }
        public short disable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<spokenLanguage> spokenLanguage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ficha> ficha { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<programs> programs { get; set; }
    }
}
