//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.DbLogistica
{
    using System;
    using System.Collections.Generic;
    
    public partial class itinerary
    {
        public string fichaId { get; set; }
        public string actividades { get; set; }
        public string lastModifiedBy { get; set; }
        public System.DateTime dateModified { get; set; }
    
        public virtual ficha ficha { get; set; }
    }
}
