//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.DbLogistica
{
    using System;
    using System.Collections.Generic;
    
    public partial class spokenLanguage
    {
        public string staff { get; set; }
        public string slanguage { get; set; }
    
        public virtual staff staff1 { get; set; }
    }
}
