//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logistica.DbLogistica
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vehicles()
        {
            this.ficha = new HashSet<ficha>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public short contractType { get; set; }
        public string lessor { get; set; }
        public short capacity { get; set; }
        public short vyear { get; set; }
        public string insuranceCompany { get; set; }
        public string insuranceNumber { get; set; }
        public short insuranceType { get; set; }
        public string contactPhone { get; set; }
        public short disable { get; set; }
        public string lastModifiedBy { get; set; }
        public System.DateTime dateModified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ficha> ficha { get; set; }
    }
}
